"""empty message

Revision ID: 889abea60f0e
Revises: a1f56c154c9a
Create Date: 2023-04-28 22:32:13.988665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889abea60f0e'
down_revision = 'a1f56c154c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
